//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemePark.Application.entinfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="entinfoServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMS(string sn, string pwd, string mobile, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSAsync(string sn, string pwd, string mobile, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_R", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMS_R(string sn, string pwd, string mobile, string content, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_R", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMS_RAsync(string sn, string pwd, string mobile, string content, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSEx(string sn, string pwd, string mobile, string content, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSEx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSExAsync(string sn, string pwd, string mobile, string content, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSEx_R", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSEx_R(string sn, string pwd, string mobile, string content, string subcode, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSEx_R", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSEx_RAsync(string sn, string pwd, string mobile, string content, string subcode, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UnRegister(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UnRegisterAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChargUp(string sn, string pwd, string cardno, string cardpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargUp", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChargUpAsync(string sn, string pwd, string cardno, string cardpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBalance(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBalanceAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStatus(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetStatusAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCode(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCodeAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UDPPwd(string sn, string pwd, string newpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UDPPwdAsync(string sn, string pwd, string newpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPSIGN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UDPSIGN(string sn, string pwd, string sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPSIGN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UDPSIGNAsync(string sn, string pwd, string sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPSIGNEX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UDPSIGNEX(string sn, string pwd, string subcode, string sign, string comName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UDPSIGNEX", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UDPSIGNEXAsync(string sn, string pwd, string subcode, string sign, string comName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.MOBody[] RECSMS(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMSEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.MOBody[] RECSMSEx(string sn, string pwd, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMSEx", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSExAsync(string sn, string pwd, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMS_UTF8", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.MOBody[] RECSMS_UTF8(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMS_UTF8", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMS_UTF8Async(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMSEx_UTF8", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.MOBody[] RECSMSEx_UTF8(string sn, string pwd, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RECSMSEx_UTF8", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSEx_UTF8Async(string sn, string pwd, string subcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Register(string sn, string pwd, string province, string city, string trade, string entname, string linkman, string phone, string mobile, string email, string fax, string address, string postcode, string sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegisterAsync(string sn, string pwd, string province, string city, string trade, string entname, string linkman, string phone, string mobile, string email, string fax, string address, string postcode, string sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFlag(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlag", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFlagAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SMSTest(string sn, string pwd, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSTest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SMSTestAsync(string sn, string pwd, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestCode(string content, string code, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestCodeAsync(string content, string code, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.RegistryInfo GetAllInfo(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.RegistryInfo> GetAllInfoAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllInfo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ThemePark.Application.entinfoServiceReference.RegistryInfo2 GetAllInfo2(string sn, string pwd, string ver, string oem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllInfo2", ReplyAction="*")]
        System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.RegistryInfo2> GetAllInfo2Async(string sn, string pwd, string ver, string oem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetGaoDuan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double SetGaoDuan(string sn, string pwd, string gd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetGaoDuan", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SetGaoDuanAsync(string sn, string pwd, string gd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaoDuan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGaoDuan(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaoDuan", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGaoDuanAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mt(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mtAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdSmsSend(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdSmsSendAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_u", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdSmsSend_u(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_u", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdSmsSend_uAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_DES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdSmsSend_DES(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_DES", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdSmsSend_DESAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_AES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdSmsSend_AES(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_AES", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdSmsSend_AESAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_g", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdSmsSend_g(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdSmsSend_g", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdSmsSend_gAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mo(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> moAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mo2(string sn, string pwd, int maxID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mo2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mo2Async(string sn, string pwd, int maxID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string report(string sn, string pwd, long maxid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report", ReplyAction="*")]
        System.Threading.Tasks.Task<string> reportAsync(string sn, string pwd, long maxid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string report2(string sn, string pwd, long maxid, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> report2Async(string sn, string pwd, long maxid, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report2DES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string report2DES(string sn, string pwd, long maxid, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report2DES", ReplyAction="*")]
        System.Threading.Tasks.Task<string> report2DESAsync(string sn, string pwd, long maxid, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/msgid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string msgid(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/msgid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> msgidAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/balance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string balance(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/balance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> balanceAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gxmt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string gxmt(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gxmt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> gxmtAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileMT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string fileMT(string sn, string pwd, string fname, string rrid, int sort, int total, int ftype, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileMT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> fileMTAsync(string sn, string pwd, string fname, string rrid, int sort, int total, int ftype, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mmsFileMT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mmsFileMT(string sn, string pwd, string rrid, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mmsFileMT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mmsFileMTAsync(string sn, string pwd, string rrid, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdMmsSend(string sn, string pwd, string title, string mobile, string content, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdMmsSendAsync(string sn, string pwd, string title, string mobile, string content, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend_ex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdMmsSend_ex(string sn, string pwd, string title, string mobile, string content, string stime, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend_ex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdMmsSend_exAsync(string sn, string pwd, string title, string mobile, string content, string stime, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend_uex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdMmsSend_uex(string sn, string pwd, string title, string mobile, string content, string stime, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSend_uex", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdMmsSend_uexAsync(string sn, string pwd, string title, string mobile, string content, string stime, string ext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSendF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdMmsSendF(string sn, string pwd, string mobile, string content, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsSendF", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdMmsSendFAsync(string sn, string pwd, string mobile, string content, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdAudioSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdAudioSend(string sn, string pwd, string title, string mobile, string txt, string content, string srcnumber, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdAudioSend", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdAudioSendAsync(string sn, string pwd, string title, string mobile, string txt, string content, string srcnumber, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdFaxSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdFaxSend(string sn, string pwd, string title, string mobile, string content, string srcnumber, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdFaxSend", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdFaxSendAsync(string sn, string pwd, string title, string mobile, string content, string srcnumber, string stime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string mdMmsReceive(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mdMmsReceive", ReplyAction="*")]
        System.Threading.Tasks.Task<string> mdMmsReceiveAsync(string sn, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MongateCsSpSendSmsNew(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MongateCsSpSendSmsNewAsync(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] MongateCsGetSmsExEx(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> MongateCsGetSmsExExAsync(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] MongateCsGetStatusReportExEx(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> MongateCsGetStatusReportExExAsync(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bianliang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bianliang(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid, string bcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bianliang", ReplyAction="*")]
        System.Threading.Tasks.Task<string> bianliangAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid, string bcode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MOBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string total_numField;
        
        private string this_numField;
        
        private string recvtelField;
        
        private string senderField;
        
        private string contentField;
        
        private string recdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string total_num {
            get {
                return this.total_numField;
            }
            set {
                this.total_numField = value;
                this.RaisePropertyChanged("total_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string this_num {
            get {
                return this.this_numField;
            }
            set {
                this.this_numField = value;
                this.RaisePropertyChanged("this_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string recvtel {
            get {
                return this.recvtelField;
            }
            set {
                this.recvtelField = value;
                this.RaisePropertyChanged("recvtel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string recdate {
            get {
                return this.recdateField;
            }
            set {
                this.recdateField = value;
                this.RaisePropertyChanged("recdate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistryInfo2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rESULTField;
        
        private string rEGISTRYCODEField;
        
        private string sERVICECODEField;
        
        private string bALANCEField;
        
        private string cREATEDATEField;
        
        private string rEGISTRYSTATEIDField;
        
        private string pRIORITYField;
        
        private string fIRSTREGISTRYDATEField;
        
        private string rEGISTRYDATEField;
        
        private string aGENTIDField;
        
        private string pRODUCTNAMEField;
        
        private string dESTMOBILEField;
        
        private string fLAGField;
        
        private string rEPLYCONTENTField;
        
        private string iSRETURNField;
        
        private string vERSIONField;
        
        private string gRADEField;
        
        private string pARENTField;
        
        private string sUBSIDIARYField;
        
        private string rOLESField;
        
        private string bALSTATUSField;
        
        private string dISCOUNTField;
        
        private string sLISTField;
        
        private string pOPMField;
        
        private string uPDATEField;
        
        private string mMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string REGISTRYCODE {
            get {
                return this.rEGISTRYCODEField;
            }
            set {
                this.rEGISTRYCODEField = value;
                this.RaisePropertyChanged("REGISTRYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SERVICECODE {
            get {
                return this.sERVICECODEField;
            }
            set {
                this.sERVICECODEField = value;
                this.RaisePropertyChanged("SERVICECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BALANCE {
            get {
                return this.bALANCEField;
            }
            set {
                this.bALANCEField = value;
                this.RaisePropertyChanged("BALANCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
                this.RaisePropertyChanged("CREATEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string REGISTRYSTATEID {
            get {
                return this.rEGISTRYSTATEIDField;
            }
            set {
                this.rEGISTRYSTATEIDField = value;
                this.RaisePropertyChanged("REGISTRYSTATEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PRIORITY {
            get {
                return this.pRIORITYField;
            }
            set {
                this.pRIORITYField = value;
                this.RaisePropertyChanged("PRIORITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FIRSTREGISTRYDATE {
            get {
                return this.fIRSTREGISTRYDATEField;
            }
            set {
                this.fIRSTREGISTRYDATEField = value;
                this.RaisePropertyChanged("FIRSTREGISTRYDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string REGISTRYDATE {
            get {
                return this.rEGISTRYDATEField;
            }
            set {
                this.rEGISTRYDATEField = value;
                this.RaisePropertyChanged("REGISTRYDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AGENTID {
            get {
                return this.aGENTIDField;
            }
            set {
                this.aGENTIDField = value;
                this.RaisePropertyChanged("AGENTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
                this.RaisePropertyChanged("PRODUCTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DESTMOBILE {
            get {
                return this.dESTMOBILEField;
            }
            set {
                this.dESTMOBILEField = value;
                this.RaisePropertyChanged("DESTMOBILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FLAG {
            get {
                return this.fLAGField;
            }
            set {
                this.fLAGField = value;
                this.RaisePropertyChanged("FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string REPLYCONTENT {
            get {
                return this.rEPLYCONTENTField;
            }
            set {
                this.rEPLYCONTENTField = value;
                this.RaisePropertyChanged("REPLYCONTENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ISRETURN {
            get {
                return this.iSRETURNField;
            }
            set {
                this.iSRETURNField = value;
                this.RaisePropertyChanged("ISRETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
                this.RaisePropertyChanged("VERSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GRADE {
            get {
                return this.gRADEField;
            }
            set {
                this.gRADEField = value;
                this.RaisePropertyChanged("GRADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PARENT {
            get {
                return this.pARENTField;
            }
            set {
                this.pARENTField = value;
                this.RaisePropertyChanged("PARENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SUBSIDIARY {
            get {
                return this.sUBSIDIARYField;
            }
            set {
                this.sUBSIDIARYField = value;
                this.RaisePropertyChanged("SUBSIDIARY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ROLES {
            get {
                return this.rOLESField;
            }
            set {
                this.rOLESField = value;
                this.RaisePropertyChanged("ROLES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string BALSTATUS {
            get {
                return this.bALSTATUSField;
            }
            set {
                this.bALSTATUSField = value;
                this.RaisePropertyChanged("BALSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DISCOUNT {
            get {
                return this.dISCOUNTField;
            }
            set {
                this.dISCOUNTField = value;
                this.RaisePropertyChanged("DISCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SLIST {
            get {
                return this.sLISTField;
            }
            set {
                this.sLISTField = value;
                this.RaisePropertyChanged("SLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string POPM {
            get {
                return this.pOPMField;
            }
            set {
                this.pOPMField = value;
                this.RaisePropertyChanged("POPM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UPDATE {
            get {
                return this.uPDATEField;
            }
            set {
                this.uPDATEField = value;
                this.RaisePropertyChanged("UPDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string MMS {
            get {
                return this.mMSField;
            }
            set {
                this.mMSField = value;
                this.RaisePropertyChanged("MMS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistryInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rESULTField;
        
        private string rEGISTRYCODEField;
        
        private string sERVICECODEField;
        
        private string bALANCEField;
        
        private string cREATEDATEField;
        
        private string rEGISTRYSTATEIDField;
        
        private string pRIORITYField;
        
        private string fIRSTREGISTRYDATEField;
        
        private string rEGISTRYDATEField;
        
        private string aGENTIDField;
        
        private string pRODUCTNAMEField;
        
        private string dESTMOBILEField;
        
        private string fLAGField;
        
        private string rEPLYCONTENTField;
        
        private string iSRETURNField;
        
        private string vERSIONField;
        
        private string gRADEField;
        
        private string pARENTField;
        
        private string sUBSIDIARYField;
        
        private string rOLESField;
        
        private string bALSTATUSField;
        
        private string dISCOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string REGISTRYCODE {
            get {
                return this.rEGISTRYCODEField;
            }
            set {
                this.rEGISTRYCODEField = value;
                this.RaisePropertyChanged("REGISTRYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SERVICECODE {
            get {
                return this.sERVICECODEField;
            }
            set {
                this.sERVICECODEField = value;
                this.RaisePropertyChanged("SERVICECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BALANCE {
            get {
                return this.bALANCEField;
            }
            set {
                this.bALANCEField = value;
                this.RaisePropertyChanged("BALANCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
                this.RaisePropertyChanged("CREATEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string REGISTRYSTATEID {
            get {
                return this.rEGISTRYSTATEIDField;
            }
            set {
                this.rEGISTRYSTATEIDField = value;
                this.RaisePropertyChanged("REGISTRYSTATEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PRIORITY {
            get {
                return this.pRIORITYField;
            }
            set {
                this.pRIORITYField = value;
                this.RaisePropertyChanged("PRIORITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FIRSTREGISTRYDATE {
            get {
                return this.fIRSTREGISTRYDATEField;
            }
            set {
                this.fIRSTREGISTRYDATEField = value;
                this.RaisePropertyChanged("FIRSTREGISTRYDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string REGISTRYDATE {
            get {
                return this.rEGISTRYDATEField;
            }
            set {
                this.rEGISTRYDATEField = value;
                this.RaisePropertyChanged("REGISTRYDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AGENTID {
            get {
                return this.aGENTIDField;
            }
            set {
                this.aGENTIDField = value;
                this.RaisePropertyChanged("AGENTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
                this.RaisePropertyChanged("PRODUCTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DESTMOBILE {
            get {
                return this.dESTMOBILEField;
            }
            set {
                this.dESTMOBILEField = value;
                this.RaisePropertyChanged("DESTMOBILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FLAG {
            get {
                return this.fLAGField;
            }
            set {
                this.fLAGField = value;
                this.RaisePropertyChanged("FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string REPLYCONTENT {
            get {
                return this.rEPLYCONTENTField;
            }
            set {
                this.rEPLYCONTENTField = value;
                this.RaisePropertyChanged("REPLYCONTENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ISRETURN {
            get {
                return this.iSRETURNField;
            }
            set {
                this.iSRETURNField = value;
                this.RaisePropertyChanged("ISRETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
                this.RaisePropertyChanged("VERSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GRADE {
            get {
                return this.gRADEField;
            }
            set {
                this.gRADEField = value;
                this.RaisePropertyChanged("GRADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PARENT {
            get {
                return this.pARENTField;
            }
            set {
                this.pARENTField = value;
                this.RaisePropertyChanged("PARENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SUBSIDIARY {
            get {
                return this.sUBSIDIARYField;
            }
            set {
                this.sUBSIDIARYField = value;
                this.RaisePropertyChanged("SUBSIDIARY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ROLES {
            get {
                return this.rOLESField;
            }
            set {
                this.rOLESField = value;
                this.RaisePropertyChanged("ROLES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string BALSTATUS {
            get {
                return this.bALSTATUSField;
            }
            set {
                this.bALSTATUSField = value;
                this.RaisePropertyChanged("BALSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DISCOUNT {
            get {
                return this.dISCOUNTField;
            }
            set {
                this.dISCOUNTField = value;
                this.RaisePropertyChanged("DISCOUNT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ThemePark.Application.entinfoServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ThemePark.Application.entinfoServiceReference.WebServiceSoap>, ThemePark.Application.entinfoServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSMS(string sn, string pwd, string mobile, string content) {
            return base.Channel.SendSMS(sn, pwd, mobile, content);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSAsync(string sn, string pwd, string mobile, string content) {
            return base.Channel.SendSMSAsync(sn, pwd, mobile, content);
        }
        
        public string SendSMS_R(string sn, string pwd, string mobile, string content, string rrid) {
            return base.Channel.SendSMS_R(sn, pwd, mobile, content, rrid);
        }
        
        public System.Threading.Tasks.Task<string> SendSMS_RAsync(string sn, string pwd, string mobile, string content, string rrid) {
            return base.Channel.SendSMS_RAsync(sn, pwd, mobile, content, rrid);
        }
        
        public string SendSMSEx(string sn, string pwd, string mobile, string content, string subcode) {
            return base.Channel.SendSMSEx(sn, pwd, mobile, content, subcode);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSExAsync(string sn, string pwd, string mobile, string content, string subcode) {
            return base.Channel.SendSMSExAsync(sn, pwd, mobile, content, subcode);
        }
        
        public string SendSMSEx_R(string sn, string pwd, string mobile, string content, string subcode, string rrid) {
            return base.Channel.SendSMSEx_R(sn, pwd, mobile, content, subcode, rrid);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSEx_RAsync(string sn, string pwd, string mobile, string content, string subcode, string rrid) {
            return base.Channel.SendSMSEx_RAsync(sn, pwd, mobile, content, subcode, rrid);
        }
        
        public string UnRegister(string sn, string pwd) {
            return base.Channel.UnRegister(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> UnRegisterAsync(string sn, string pwd) {
            return base.Channel.UnRegisterAsync(sn, pwd);
        }
        
        public string ChargUp(string sn, string pwd, string cardno, string cardpwd) {
            return base.Channel.ChargUp(sn, pwd, cardno, cardpwd);
        }
        
        public System.Threading.Tasks.Task<string> ChargUpAsync(string sn, string pwd, string cardno, string cardpwd) {
            return base.Channel.ChargUpAsync(sn, pwd, cardno, cardpwd);
        }
        
        public string GetBalance(string sn, string pwd) {
            return base.Channel.GetBalance(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> GetBalanceAsync(string sn, string pwd) {
            return base.Channel.GetBalanceAsync(sn, pwd);
        }
        
        public string GetStatus(string sn, string pwd) {
            return base.Channel.GetStatus(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> GetStatusAsync(string sn, string pwd) {
            return base.Channel.GetStatusAsync(sn, pwd);
        }
        
        public string GetCode(string sn, string pwd) {
            return base.Channel.GetCode(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> GetCodeAsync(string sn, string pwd) {
            return base.Channel.GetCodeAsync(sn, pwd);
        }
        
        public string UDPPwd(string sn, string pwd, string newpwd) {
            return base.Channel.UDPPwd(sn, pwd, newpwd);
        }
        
        public System.Threading.Tasks.Task<string> UDPPwdAsync(string sn, string pwd, string newpwd) {
            return base.Channel.UDPPwdAsync(sn, pwd, newpwd);
        }
        
        public string UDPSIGN(string sn, string pwd, string sign) {
            return base.Channel.UDPSIGN(sn, pwd, sign);
        }
        
        public System.Threading.Tasks.Task<string> UDPSIGNAsync(string sn, string pwd, string sign) {
            return base.Channel.UDPSIGNAsync(sn, pwd, sign);
        }
        
        public string UDPSIGNEX(string sn, string pwd, string subcode, string sign, string comName) {
            return base.Channel.UDPSIGNEX(sn, pwd, subcode, sign, comName);
        }
        
        public System.Threading.Tasks.Task<string> UDPSIGNEXAsync(string sn, string pwd, string subcode, string sign, string comName) {
            return base.Channel.UDPSIGNEXAsync(sn, pwd, subcode, sign, comName);
        }
        
        public ThemePark.Application.entinfoServiceReference.MOBody[] RECSMS(string sn, string pwd) {
            return base.Channel.RECSMS(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSAsync(string sn, string pwd) {
            return base.Channel.RECSMSAsync(sn, pwd);
        }
        
        public ThemePark.Application.entinfoServiceReference.MOBody[] RECSMSEx(string sn, string pwd, string subcode) {
            return base.Channel.RECSMSEx(sn, pwd, subcode);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSExAsync(string sn, string pwd, string subcode) {
            return base.Channel.RECSMSExAsync(sn, pwd, subcode);
        }
        
        public ThemePark.Application.entinfoServiceReference.MOBody[] RECSMS_UTF8(string sn, string pwd) {
            return base.Channel.RECSMS_UTF8(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMS_UTF8Async(string sn, string pwd) {
            return base.Channel.RECSMS_UTF8Async(sn, pwd);
        }
        
        public ThemePark.Application.entinfoServiceReference.MOBody[] RECSMSEx_UTF8(string sn, string pwd, string subcode) {
            return base.Channel.RECSMSEx_UTF8(sn, pwd, subcode);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.MOBody[]> RECSMSEx_UTF8Async(string sn, string pwd, string subcode) {
            return base.Channel.RECSMSEx_UTF8Async(sn, pwd, subcode);
        }
        
        public string Register(string sn, string pwd, string province, string city, string trade, string entname, string linkman, string phone, string mobile, string email, string fax, string address, string postcode, string sign) {
            return base.Channel.Register(sn, pwd, province, city, trade, entname, linkman, phone, mobile, email, fax, address, postcode, sign);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string sn, string pwd, string province, string city, string trade, string entname, string linkman, string phone, string mobile, string email, string fax, string address, string postcode, string sign) {
            return base.Channel.RegisterAsync(sn, pwd, province, city, trade, entname, linkman, phone, mobile, email, fax, address, postcode, sign);
        }
        
        public string GetFlag(string sn, string pwd) {
            return base.Channel.GetFlag(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> GetFlagAsync(string sn, string pwd) {
            return base.Channel.GetFlagAsync(sn, pwd);
        }
        
        public string SMSTest(string sn, string pwd, string mobile) {
            return base.Channel.SMSTest(sn, pwd, mobile);
        }
        
        public System.Threading.Tasks.Task<string> SMSTestAsync(string sn, string pwd, string mobile) {
            return base.Channel.SMSTestAsync(sn, pwd, mobile);
        }
        
        public string TestCode(string content, string code, string type) {
            return base.Channel.TestCode(content, code, type);
        }
        
        public System.Threading.Tasks.Task<string> TestCodeAsync(string content, string code, string type) {
            return base.Channel.TestCodeAsync(content, code, type);
        }
        
        public ThemePark.Application.entinfoServiceReference.RegistryInfo GetAllInfo(string sn, string pwd) {
            return base.Channel.GetAllInfo(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.RegistryInfo> GetAllInfoAsync(string sn, string pwd) {
            return base.Channel.GetAllInfoAsync(sn, pwd);
        }
        
        public ThemePark.Application.entinfoServiceReference.RegistryInfo2 GetAllInfo2(string sn, string pwd, string ver, string oem) {
            return base.Channel.GetAllInfo2(sn, pwd, ver, oem);
        }
        
        public System.Threading.Tasks.Task<ThemePark.Application.entinfoServiceReference.RegistryInfo2> GetAllInfo2Async(string sn, string pwd, string ver, string oem) {
            return base.Channel.GetAllInfo2Async(sn, pwd, ver, oem);
        }
        
        public double SetGaoDuan(string sn, string pwd, string gd) {
            return base.Channel.SetGaoDuan(sn, pwd, gd);
        }
        
        public System.Threading.Tasks.Task<double> SetGaoDuanAsync(string sn, string pwd, string gd) {
            return base.Channel.SetGaoDuanAsync(sn, pwd, gd);
        }
        
        public string GetGaoDuan(string sn, string pwd) {
            return base.Channel.GetGaoDuan(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> GetGaoDuanAsync(string sn, string pwd) {
            return base.Channel.GetGaoDuanAsync(sn, pwd);
        }
        
        public string mt(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mt(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mtAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mtAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mdSmsSend(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mdSmsSendAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSendAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mdSmsSend_u(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_u(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mdSmsSend_uAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_uAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mdSmsSend_DES(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_DES(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mdSmsSend_DESAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_DESAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mdSmsSend_AES(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_AES(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mdSmsSend_AESAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_AESAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mdSmsSend_g(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_g(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> mdSmsSend_gAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.mdSmsSend_gAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string mo(string sn, string pwd) {
            return base.Channel.mo(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> moAsync(string sn, string pwd) {
            return base.Channel.moAsync(sn, pwd);
        }
        
        public string mo2(string sn, string pwd, int maxID) {
            return base.Channel.mo2(sn, pwd, maxID);
        }
        
        public System.Threading.Tasks.Task<string> mo2Async(string sn, string pwd, int maxID) {
            return base.Channel.mo2Async(sn, pwd, maxID);
        }
        
        public string report(string sn, string pwd, long maxid) {
            return base.Channel.report(sn, pwd, maxid);
        }
        
        public System.Threading.Tasks.Task<string> reportAsync(string sn, string pwd, long maxid) {
            return base.Channel.reportAsync(sn, pwd, maxid);
        }
        
        public string report2(string sn, string pwd, long maxid, string rrid) {
            return base.Channel.report2(sn, pwd, maxid, rrid);
        }
        
        public System.Threading.Tasks.Task<string> report2Async(string sn, string pwd, long maxid, string rrid) {
            return base.Channel.report2Async(sn, pwd, maxid, rrid);
        }
        
        public string report2DES(string sn, string pwd, long maxid, string rrid) {
            return base.Channel.report2DES(sn, pwd, maxid, rrid);
        }
        
        public System.Threading.Tasks.Task<string> report2DESAsync(string sn, string pwd, long maxid, string rrid) {
            return base.Channel.report2DESAsync(sn, pwd, maxid, rrid);
        }
        
        public string msgid(string sn, string pwd) {
            return base.Channel.msgid(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> msgidAsync(string sn, string pwd) {
            return base.Channel.msgidAsync(sn, pwd);
        }
        
        public string balance(string sn, string pwd) {
            return base.Channel.balance(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> balanceAsync(string sn, string pwd) {
            return base.Channel.balanceAsync(sn, pwd);
        }
        
        public string gxmt(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.gxmt(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public System.Threading.Tasks.Task<string> gxmtAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid) {
            return base.Channel.gxmtAsync(sn, pwd, mobile, content, ext, stime, rrid);
        }
        
        public string fileMT(string sn, string pwd, string fname, string rrid, int sort, int total, int ftype, string content) {
            return base.Channel.fileMT(sn, pwd, fname, rrid, sort, total, ftype, content);
        }
        
        public System.Threading.Tasks.Task<string> fileMTAsync(string sn, string pwd, string fname, string rrid, int sort, int total, int ftype, string content) {
            return base.Channel.fileMTAsync(sn, pwd, fname, rrid, sort, total, ftype, content);
        }
        
        public string mmsFileMT(string sn, string pwd, string rrid, string content) {
            return base.Channel.mmsFileMT(sn, pwd, rrid, content);
        }
        
        public System.Threading.Tasks.Task<string> mmsFileMTAsync(string sn, string pwd, string rrid, string content) {
            return base.Channel.mmsFileMTAsync(sn, pwd, rrid, content);
        }
        
        public string mdMmsSend(string sn, string pwd, string title, string mobile, string content, string stime) {
            return base.Channel.mdMmsSend(sn, pwd, title, mobile, content, stime);
        }
        
        public System.Threading.Tasks.Task<string> mdMmsSendAsync(string sn, string pwd, string title, string mobile, string content, string stime) {
            return base.Channel.mdMmsSendAsync(sn, pwd, title, mobile, content, stime);
        }
        
        public string mdMmsSend_ex(string sn, string pwd, string title, string mobile, string content, string stime, string ext) {
            return base.Channel.mdMmsSend_ex(sn, pwd, title, mobile, content, stime, ext);
        }
        
        public System.Threading.Tasks.Task<string> mdMmsSend_exAsync(string sn, string pwd, string title, string mobile, string content, string stime, string ext) {
            return base.Channel.mdMmsSend_exAsync(sn, pwd, title, mobile, content, stime, ext);
        }
        
        public string mdMmsSend_uex(string sn, string pwd, string title, string mobile, string content, string stime, string ext) {
            return base.Channel.mdMmsSend_uex(sn, pwd, title, mobile, content, stime, ext);
        }
        
        public System.Threading.Tasks.Task<string> mdMmsSend_uexAsync(string sn, string pwd, string title, string mobile, string content, string stime, string ext) {
            return base.Channel.mdMmsSend_uexAsync(sn, pwd, title, mobile, content, stime, ext);
        }
        
        public string mdMmsSendF(string sn, string pwd, string mobile, string content, string stime) {
            return base.Channel.mdMmsSendF(sn, pwd, mobile, content, stime);
        }
        
        public System.Threading.Tasks.Task<string> mdMmsSendFAsync(string sn, string pwd, string mobile, string content, string stime) {
            return base.Channel.mdMmsSendFAsync(sn, pwd, mobile, content, stime);
        }
        
        public string mdAudioSend(string sn, string pwd, string title, string mobile, string txt, string content, string srcnumber, string stime) {
            return base.Channel.mdAudioSend(sn, pwd, title, mobile, txt, content, srcnumber, stime);
        }
        
        public System.Threading.Tasks.Task<string> mdAudioSendAsync(string sn, string pwd, string title, string mobile, string txt, string content, string srcnumber, string stime) {
            return base.Channel.mdAudioSendAsync(sn, pwd, title, mobile, txt, content, srcnumber, stime);
        }
        
        public string mdFaxSend(string sn, string pwd, string title, string mobile, string content, string srcnumber, string stime) {
            return base.Channel.mdFaxSend(sn, pwd, title, mobile, content, srcnumber, stime);
        }
        
        public System.Threading.Tasks.Task<string> mdFaxSendAsync(string sn, string pwd, string title, string mobile, string content, string srcnumber, string stime) {
            return base.Channel.mdFaxSendAsync(sn, pwd, title, mobile, content, srcnumber, stime);
        }
        
        public string mdMmsReceive(string sn, string pwd) {
            return base.Channel.mdMmsReceive(sn, pwd);
        }
        
        public System.Threading.Tasks.Task<string> mdMmsReceiveAsync(string sn, string pwd) {
            return base.Channel.mdMmsReceiveAsync(sn, pwd);
        }
        
        public string MongateCsSpSendSmsNew(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort) {
            return base.Channel.MongateCsSpSendSmsNew(userId, password, pszMobis, pszMsg, iMobiCount, pszSubPort);
        }
        
        public System.Threading.Tasks.Task<string> MongateCsSpSendSmsNewAsync(string userId, string password, string pszMobis, string pszMsg, int iMobiCount, string pszSubPort) {
            return base.Channel.MongateCsSpSendSmsNewAsync(userId, password, pszMobis, pszMsg, iMobiCount, pszSubPort);
        }
        
        public string[] MongateCsGetSmsExEx(string userId, string password) {
            return base.Channel.MongateCsGetSmsExEx(userId, password);
        }
        
        public System.Threading.Tasks.Task<string[]> MongateCsGetSmsExExAsync(string userId, string password) {
            return base.Channel.MongateCsGetSmsExExAsync(userId, password);
        }
        
        public string[] MongateCsGetStatusReportExEx(string userId, string password) {
            return base.Channel.MongateCsGetStatusReportExEx(userId, password);
        }
        
        public System.Threading.Tasks.Task<string[]> MongateCsGetStatusReportExExAsync(string userId, string password) {
            return base.Channel.MongateCsGetStatusReportExExAsync(userId, password);
        }
        
        public string bianliang(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid, string bcode) {
            return base.Channel.bianliang(sn, pwd, mobile, content, ext, stime, rrid, bcode);
        }
        
        public System.Threading.Tasks.Task<string> bianliangAsync(string sn, string pwd, string mobile, string content, string ext, string stime, string rrid, string bcode) {
            return base.Channel.bianliangAsync(sn, pwd, mobile, content, ext, stime, rrid, bcode);
        }
    }
}
